language: objective-c
osx_image: xcode8
cache: cocoapods

env:
  global:
  - LANG=en_US.UTF-8

  - WORKSPACE="OTAcceleratorCore.xcworkspace"
  - IOS_SCHEME="OTAcceleratorCore"
  - IOS_SDK=iphonesimulator10.0

  matrix:
  #- DESTINATION="OS=9.0,name=iPhone 6 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES" RUN_UI_TESTS="NO"
  #- DESTINATION="OS=9.1,name=iPhone 6s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"
  #- DESTINATION="OS=9.2,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"
  - DESTINATION="OS=9.3,name=iPad Air 2"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"

  - DESTINATION="OS=10.0,name=iPhone 6s"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES" RUN_UI_TESTS="NO"

before_install:
  - gem install cocoapods --pre
  - pod install

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
    pod lib lint --use-libraries --allow-warnings --verbose;
  fi

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
    xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

notifications:
  slack:
    secure: ipGaZDivkGwHM5lFH0PKsHjORMTF4h6tF5Uq6axvXIWdxFUVhFLMrdWlrZrdNGnpPc3/TD4ZJ7HnC8K3cfzNp/nuQEDEpXxetGZXKx8QFJrHxneqVAVH+TWmSKHAGfBQvxPUSTYASKY+ghvTm2yTwjoVILfC3cx0U6nMgCUI03MSQvoYTTucX48zuF5/YP6P4DFyPgFAKldawZImz/Fjk/7wVZcsdHGii7dQlc4yd7JUZbZ2xMI8doVsDYN7CFV0clWzchkXLTEKrniN7ML6MpGeDPGMK2wN7fi/VBzMGzrsOfEATh3SEqlKKKzSiOXx1IoIC7r3qvSyeYtzMceFpkdYeVJq4+38EMpE7peFi0zkce1N1cDyYbL4PLMA4mp1PKzAe3lppIl1iEJsE9gqVsbRLWvn87Ie51vz83pE5bebGXFo84A8/FMq+PM9YnUrT9yeOKofQ3BRyI/VLf+UzVmbEgcdBOGTas0+gYw2NNQ//3bKJkbuetMSO8G7kegVdG01KV9pkvknlCVKNufGMEyIumVGOs7odlgry3+sdHDPm5rWcwuyM6OD6uZRIgrhb8BX1wTwT6oALzKgpLkqdoTJyPP9mr7xUx5w5OYS4udM/EBaf6h9OPePzJyjsarhqAZUAXubwAls7pmJelxoSxHVjsLOKMdM1hw3P+kYzGY=
