language: objective-c
osx_image: xcode8
cache: cocoapods

env:
  global:
  - LANG=en_US.UTF-8

  - WORKSPACE="OTAcceleratorCore.xcworkspace"
  - IOS_SCHEME="OTAcceleratorCore"
  - IOS_SDK=iphonesimulator10.0

  matrix:
  - DESTINATION="OS=9.0,name=iPhone 6 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES" RUN_UI_TESTS="NO"
  - DESTINATION="OS=9.1,name=iPhone 6s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"
  - DESTINATION="OS=9.2,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"
  - DESTINATION="OS=9.3,name=iPad Air 2"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"

  - DESTINATION="OS=10.0,name=iPhone 6s"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES" RUN_UI_TESTS="NO"

before_install:
  - gem install cocoapods --pre
  - pod install

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
    pod lib lint --use-libraries --allow-warnings --verbose;
  fi

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
    xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

